version: "3.9"  # optional since v1.27.0
networks:
  df-labs-net:
    name: df-labs-net
    external: true
services:
  df-labs-web-service:
    build: .
    image: df-labs/web-service
    container_name: df-labs-web-service
    ports:
      - "8888:8888"
    networks:
      - df-labs-net
#    restart: always
